version: '3.7'

services:
  minio:
    image: minio/minio:RELEASE.2023-07-21T21-12-44Z.fips
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"

  mc:
    image: minio/mc:RELEASE.2023-07-21T20-44-27Z
    depends_on:
      - minio
    # restart: on-failure
    entrypoint: >
      sh -c "
        mc alias set mine http://minio:9000 minioadmin minioadmin
        mc mb --ignore-existing mine/s3zip-test
        mc admin policy attach mine readwrite mine/s3zip-test --user minioadmin
      "
